### ISSUE TITLE
gayleeba frontis gasworeba

### ISSUE THREAD

**Issue by gugakatsi** [mishotek/savele2017#2]

**Comment by mishotek** [comment]
magari satauria :D :D

**Comment by gugakatsi** [comment]
@mishotek :D git pull da gaaswore

**Comment by mishotek** [comment]
axla unishi mividvar da shualedi rom meqneba gavasworeb
da ra gavasworo momwere konkretulad im listis garda rame gchirdeba?

**Comment by gugakatsi** [comment]
@mishotek 
* sign in button chamowie dabla da magis div-shi racaa yvelpaeri da savele2017 ro aweria gauswore magas
* da inputi sheni lokaciis shecvale select-boxit
